import { db } from "./db";
import {
  rooms, users, contents, quizQuestions, missions,
  commentsTable, badges, activities, roomPosts
} from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  try {
    const result = await db.execute(sql`SELECT count(*)::int as count FROM rooms`);
    const count = (result.rows[0] as any)?.count ?? 0;
    if (count > 0) {
      console.log("Database already seeded, skipping...");
      return;
    }

    await db.insert(rooms).values([
      { id: "room-1", name: "Labo Science", description: "Explore les mystères de la science avec des expériences passionnantes", type: "public", category: "science", imageUrl: null, memberCount: 234, createdAt: new Date().toISOString() },
      { id: "room-2", name: "Tech Makers", description: "Construis des projets tech innovants avec la communauté", type: "public", category: "technology", imageUrl: null, memberCount: 189, createdAt: new Date().toISOString() },
      { id: "room-3", name: "Ingénieurs en herbe", description: "Conçois et crée des solutions d'ingénierie", type: "public", category: "engineering", imageUrl: null, memberCount: 156, createdAt: new Date().toISOString() },
      { id: "room-4", name: "Mathématiques Fun", description: "Les maths peuvent être amusantes ! Découvre-le ici", type: "public", category: "mathematics", imageUrl: null, memberCount: 203, createdAt: new Date().toISOString() },
      { id: "room-5", name: "Robotique Club", description: "Apprends à construire et programmer des robots", type: "public", category: "technology", imageUrl: null, memberCount: 142, createdAt: new Date().toISOString() },
      { id: "room-6", name: "Astronomie", description: "Explore l'univers et ses mystères", type: "public", category: "science", imageUrl: null, memberCount: 178, createdAt: new Date().toISOString() },
    ]);

    await db.insert(users).values([
      { id: "lb-user-1", username: "Dr. Marie Curie", email: "marie@stemflow.com", password: "", isActive: true, activationCode: null, xp: 4500, level: "challenger", streak: 15, onboardingCompleted: true, preferredLanguage: "fr", educationLevel: "universite", interests: ["science"], createdAt: new Date().toISOString() },
      { id: "lb-user-2", username: "Alan Turing", email: "alan@stemflow.com", password: "", isActive: true, activationCode: null, xp: 3800, level: "analyste", streak: 22, onboardingCompleted: true, preferredLanguage: "en", educationLevel: "universite", interests: ["technology", "mathematics"], createdAt: new Date().toISOString() },
      { id: "lb-user-3", username: "Ada Lovelace", email: "ada@stemflow.com", password: "", isActive: true, activationCode: null, xp: 3200, level: "analyste", streak: 10, onboardingCompleted: true, preferredLanguage: "en", educationLevel: "universite", interests: ["technology"], createdAt: new Date().toISOString() },
      { id: "lb-user-4", username: "Pierre Fermat", email: "pierre@stemflow.com", password: "", isActive: true, activationCode: null, xp: 2900, level: "analyste", streak: 8, onboardingCompleted: true, preferredLanguage: "fr", educationLevel: "universite", interests: ["mathematics"], createdAt: new Date().toISOString() },
      { id: "lb-user-5", username: "Nikola Tesla", email: "nikola@stemflow.com", password: "", isActive: true, activationCode: null, xp: 2500, level: "explorateur", streak: 12, onboardingCompleted: true, preferredLanguage: "en", educationLevel: "universite", interests: ["engineering", "technology"], createdAt: new Date().toISOString() },
    ]);

    await db.insert(contents).values([
      { id: "content-1", contentType: "video", title: "Comment fonctionne un trou noir ?", description: "Découvre les secrets des trous noirs et leur impact sur l'espace-temps.", videoUrl: "https://www.youtube.com/watch?v=e-P5IFTqB98", textContent: null, imageUrl: null, roomId: "room-1", roomName: "Labo Science", category: "science", difficulty: "intermediaire", tags: ["#Physique", "#Espace", "#TrousNoirs"], xpReward: 35, authorId: "author-1", authorName: "TED-Ed", authorAvatar: null, likes: 456, comments: 67, shares: 34, createdAt: new Date(Date.now() - 3600000).toISOString() },
      { id: "content-9", contentType: "video", title: "Comment fonctionnent les panneaux solaires ?", description: "L'énergie solaire expliquée simplement.", videoUrl: "https://www.youtube.com/watch?v=xKxrkht7CpY", textContent: null, imageUrl: null, roomId: "room-1", roomName: "Labo Science", category: "science", difficulty: "debutant", tags: ["#Énergie", "#Solaire", "#Physique"], xpReward: 30, authorId: "author-1", authorName: "TED-Ed", authorAvatar: null, likes: 378, comments: 45, shares: 28, createdAt: new Date(Date.now() - 7200000).toISOString() },
      { id: "content-10", contentType: "video", title: "Qu'est-ce que la matière noire ?", description: "La matière noire compose 27% de l'univers.", videoUrl: "https://www.youtube.com/watch?v=HneiEA1B8ks", textContent: null, imageUrl: null, roomId: "room-6", roomName: "Astronomie", category: "science", difficulty: "avance", tags: ["#Astrophysique", "#MatièreNoire", "#Cosmologie"], xpReward: 50, authorId: "author-6", authorName: "Kurzgesagt", authorAvatar: null, likes: 534, comments: 89, shares: 67, createdAt: new Date(Date.now() - 14400000).toISOString() },
      { id: "content-11", contentType: "video", title: "Comment le cerveau traite-t-il la douleur ?", description: "Explore les mécanismes fascinants du cerveau.", videoUrl: "https://www.youtube.com/watch?v=I7wfDenj6CQ", textContent: null, imageUrl: null, roomId: "room-1", roomName: "Labo Science", category: "science", difficulty: "intermediaire", tags: ["#Neuroscience", "#Cerveau", "#Biologie"], xpReward: 35, authorId: "author-1", authorName: "TED-Ed", authorAvatar: null, likes: 289, comments: 34, shares: 21, createdAt: new Date(Date.now() - 28800000).toISOString() },
      { id: "content-12", contentType: "video", title: "La chimie de l'amour", description: "Dopamine, ocytocine, sérotonine : la science des émotions.", videoUrl: "https://www.youtube.com/watch?v=169N81xAffQ", textContent: null, imageUrl: null, roomId: "room-1", roomName: "Labo Science", category: "science", difficulty: "debutant", tags: ["#Chimie", "#Biologie", "#Émotions"], xpReward: 25, authorId: "author-1", authorName: "TED-Ed", authorAvatar: null, likes: 623, comments: 78, shares: 56, createdAt: new Date(Date.now() - 43200000).toISOString() },
      { id: "content-13", contentType: "video", title: "La gravité expliquée par le MIT", description: "La gravité expliquée par les professeurs du MIT.", videoUrl: "https://archive.org/download/MITRES.TLL-004F13/MITRES_TLL-004F13_gravity_300k.mp4", textContent: null, imageUrl: null, roomId: "room-1", roomName: "Labo Science", category: "science", difficulty: "intermediaire", tags: ["#Physique", "#Gravité", "#MIT"], xpReward: 35, authorId: "author-1", authorName: "MIT OpenCourseWare", authorAvatar: null, likes: 312, comments: 41, shares: 25, createdAt: new Date(Date.now() - 57600000).toISOString() },
      { id: "content-2", contentType: "text_post", title: "L'intelligence artificielle expliquée simplement", description: "Comprends les bases de l'IA en 5 minutes", videoUrl: null, textContent: "L'intelligence artificielle est la capacité d'une machine à imiter des comportements humains intelligents...", imageUrl: null, roomId: "room-2", roomName: "Tech Makers", category: "technology", difficulty: "debutant", tags: ["#IA", "#Tech", "#MachineLearning"], xpReward: 25, authorId: "author-2", authorName: "Alan Turing", authorAvatar: null, likes: 289, comments: 45, shares: 28, createdAt: new Date(Date.now() - 72000000).toISOString() },
      { id: "content-5", contentType: "video", title: "Programmer ton premier robot", description: "Apprends les bases de la programmation robotique avec Arduino.", videoUrl: "https://www.youtube.com/watch?v=fCxzA9_kg6s", textContent: null, imageUrl: null, roomId: "room-5", roomName: "Robotique Club", category: "technology", difficulty: "intermediaire", tags: ["#Robotique", "#Arduino", "#Code"], xpReward: 40, authorId: "author-5", authorName: "Ada Lovelace", authorAvatar: null, likes: 403, comments: 65, shares: 48, createdAt: new Date(Date.now() - 86400000).toISOString() },
      { id: "content-14", contentType: "video", title: "Le logiciel qui a envoyé l'homme sur la Lune", description: "L'histoire de Margaret Hamilton et du code Apollo 11.", videoUrl: "https://www.youtube.com/watch?v=kYCZPXSVvOQ", textContent: null, imageUrl: null, roomId: "room-2", roomName: "Tech Makers", category: "technology", difficulty: "intermediaire", tags: ["#Histoire", "#NASA", "#Code"], xpReward: 35, authorId: "author-1", authorName: "TED-Ed", authorAvatar: null, likes: 567, comments: 89, shares: 72, createdAt: new Date(Date.now() - 100800000).toISOString() },
      { id: "content-15", contentType: "video", title: "Comment fonctionne Internet ?", description: "Des câbles sous-marins aux data centers.", videoUrl: "https://www.youtube.com/watch?v=x3c1ih2NJEg", textContent: null, imageUrl: null, roomId: "room-2", roomName: "Tech Makers", category: "technology", difficulty: "debutant", tags: ["#Internet", "#Réseau", "#Web"], xpReward: 30, authorId: "author-2", authorName: "Kurzgesagt", authorAvatar: null, likes: 445, comments: 56, shares: 39, createdAt: new Date(Date.now() - 115200000).toISOString() },
      { id: "content-16", contentType: "video", title: "Qu'est-ce qu'un algorithme ?", description: "Les algorithmes dans ta vie quotidienne.", videoUrl: "https://www.youtube.com/watch?v=6hfOvs8pY1k", textContent: null, imageUrl: null, roomId: "room-2", roomName: "Tech Makers", category: "technology", difficulty: "debutant", tags: ["#Algorithme", "#Informatique", "#Logique"], xpReward: 25, authorId: "author-1", authorName: "TED-Ed", authorAvatar: null, likes: 356, comments: 42, shares: 31, createdAt: new Date(Date.now() - 129600000).toISOString() },
      { id: "content-17", contentType: "video", title: "Introduction à la programmation", description: "Les bases de la programmation par le MIT.", videoUrl: "https://archive.org/download/MITRES.TLL-004F13/MITRES_TLL-004F13_basic_programming_300k.mp4", textContent: null, imageUrl: null, roomId: "room-2", roomName: "Tech Makers", category: "technology", difficulty: "debutant", tags: ["#Programmation", "#MIT", "#Code"], xpReward: 30, authorId: "author-5", authorName: "MIT OpenCourseWare", authorAvatar: null, likes: 278, comments: 34, shares: 45, createdAt: new Date(Date.now() - 144000000).toISOString() },
      { id: "content-4", contentType: "infographic", title: "Les étapes de la construction d'un pont", description: "De la conception à la réalisation.", videoUrl: null, textContent: "La construction d'un pont suit des étapes précises...", imageUrl: null, roomId: "room-3", roomName: "Ingénieurs en herbe", category: "engineering", difficulty: "debutant", tags: ["#Génie", "#Construction", "#Ponts"], xpReward: 30, authorId: "author-4", authorName: "Gustave Eiffel", authorAvatar: null, likes: 312, comments: 39, shares: 24, createdAt: new Date(Date.now() - 158400000).toISOString() },
      { id: "content-8", contentType: "video", title: "Construis un circuit électrique", description: "Tutoriel pour créer ton premier circuit.", videoUrl: "https://www.youtube.com/watch?v=mc979OhitAg", textContent: null, imageUrl: null, roomId: "room-3", roomName: "Ingénieurs en herbe", category: "engineering", difficulty: "avance", tags: ["#Électronique", "#Circuit", "#LoiOhm"], xpReward: 60, authorId: "author-8", authorName: "Nikola Tesla", authorAvatar: null, likes: 367, comments: 58, shares: 45, createdAt: new Date(Date.now() - 172800000).toISOString() },
      { id: "content-18", contentType: "video", title: "Comment construire un gratte-ciel ?", description: "L'ingénierie derrière les plus hauts bâtiments.", videoUrl: "https://www.youtube.com/watch?v=azEvfD4c6ow", textContent: null, imageUrl: null, roomId: "room-3", roomName: "Ingénieurs en herbe", category: "engineering", difficulty: "intermediaire", tags: ["#Architecture", "#Construction", "#Ingénierie"], xpReward: 40, authorId: "author-4", authorName: "Gustave Eiffel", authorAvatar: null, likes: 423, comments: 52, shares: 38, createdAt: new Date(Date.now() - 187200000).toISOString() },
      { id: "content-19", contentType: "video", title: "La chimie au quotidien - NISE Network", description: "La chimie dans ta vie quotidienne.", videoUrl: "https://vimeo.com/399952193", textContent: null, imageUrl: null, roomId: "room-3", roomName: "Ingénieurs en herbe", category: "engineering", difficulty: "debutant", tags: ["#Chimie", "#Quotidien", "#NISE"], xpReward: 30, authorId: "author-8", authorName: "NISE Network", authorAvatar: null, likes: 298, comments: 43, shares: 32, createdAt: new Date(Date.now() - 201600000).toISOString() },
      { id: "content-20", contentType: "video", title: "Le système solaire en miniature", description: "Construis un modèle du système solaire.", videoUrl: "https://vimeo.com/850662292", textContent: null, imageUrl: null, roomId: "room-3", roomName: "Ingénieurs en herbe", category: "engineering", difficulty: "debutant", tags: ["#Espace", "#Modèle", "#NISE"], xpReward: 30, authorId: "author-4", authorName: "NISE Network", authorAvatar: null, likes: 489, comments: 67, shares: 54, createdAt: new Date(Date.now() - 216000000).toISOString() },
      { id: "content-21", contentType: "video", title: "Comment fonctionne une fusée ?", description: "La propulsion des fusées : Newton en action.", videoUrl: "https://www.youtube.com/watch?v=yvVFqt4BGck", textContent: null, imageUrl: null, roomId: "room-3", roomName: "Ingénieurs en herbe", category: "engineering", difficulty: "avance", tags: ["#Fusée", "#Propulsion", "#Espace"], xpReward: 50, authorId: "author-8", authorName: "Nikola Tesla", authorAvatar: null, likes: 534, comments: 78, shares: 61, createdAt: new Date(Date.now() - 230400000).toISOString() },
      { id: "content-3", contentType: "quiz", title: "Quiz : Les équations du second degré", description: "Teste tes connaissances sur les équations quadratiques.", videoUrl: null, textContent: null, imageUrl: null, roomId: "room-4", roomName: "Mathématiques Fun", category: "mathematics", difficulty: "intermediaire", tags: ["#Maths", "#Algèbre", "#Équations"], xpReward: 50, authorId: "author-3", authorName: "Pierre Fermat", authorAvatar: null, likes: 267, comments: 38, shares: 25, createdAt: new Date(Date.now() - 244800000).toISOString() },
      { id: "content-7", contentType: "text_post", title: "Le théorème de Pythagore dans la vraie vie", description: "Le théorème de Pythagore est utilisé tous les jours", videoUrl: null, textContent: "Le théorème de Pythagore n'est pas juste une formule scolaire...", imageUrl: null, roomId: "room-4", roomName: "Mathématiques Fun", category: "mathematics", difficulty: "debutant", tags: ["#Maths", "#Géométrie", "#Pythagore"], xpReward: 25, authorId: "author-7", authorName: "Pythagore", authorAvatar: null, likes: 378, comments: 52, shares: 38, createdAt: new Date(Date.now() - 259200000).toISOString() },
      { id: "content-22", contentType: "video", title: "La vie infinie de Pi", description: "Pi (π) fascine les mathématiciens depuis des millénaires.", videoUrl: "https://www.youtube.com/watch?v=9a5vHXsUvUw", textContent: null, imageUrl: null, roomId: "room-4", roomName: "Mathématiques Fun", category: "mathematics", difficulty: "debutant", tags: ["#Pi", "#Nombres", "#Géométrie"], xpReward: 30, authorId: "author-1", authorName: "TED-Ed", authorAvatar: null, likes: 512, comments: 73, shares: 56, createdAt: new Date(Date.now() - 273600000).toISOString() },
      { id: "content-23", contentType: "video", title: "Peux-tu résoudre l'énigme du pont ?", description: "Énigme de logique mathématique captivante.", videoUrl: "https://www.youtube.com/watch?v=7yDmGnA8Hw0", textContent: null, imageUrl: null, roomId: "room-4", roomName: "Mathématiques Fun", category: "mathematics", difficulty: "intermediaire", tags: ["#Logique", "#Énigme", "#Probabilité"], xpReward: 40, authorId: "author-1", authorName: "TED-Ed", authorAvatar: null, likes: 689, comments: 95, shares: 78, createdAt: new Date(Date.now() - 288000000).toISOString() },
      { id: "content-24", contentType: "video", title: "Pourquoi les compagnies aériennes vendent trop de billets ?", description: "La surbooking par les probabilités.", videoUrl: "https://www.youtube.com/watch?v=ZFNstNKgEDI", textContent: null, imageUrl: null, roomId: "room-4", roomName: "Mathématiques Fun", category: "mathematics", difficulty: "avance", tags: ["#Probabilité", "#Statistiques", "#Économie"], xpReward: 45, authorId: "author-1", authorName: "TED-Ed", authorAvatar: null, likes: 423, comments: 61, shares: 47, createdAt: new Date(Date.now() - 302400000).toISOString() },
      { id: "content-6", contentType: "video", title: "Les planètes du système solaire", description: "Un voyage à travers notre système solaire.", videoUrl: "https://www.youtube.com/watch?v=libKVRa01L8", textContent: null, imageUrl: null, roomId: "room-6", roomName: "Astronomie", category: "science", difficulty: "debutant", tags: ["#Espace", "#Planètes", "#Astronomie"], xpReward: 25, authorId: "author-6", authorName: "Galileo Galilei", authorAvatar: null, likes: 545, comments: 76, shares: 52, createdAt: new Date(Date.now() - 316800000).toISOString() },
    ]);

    await db.insert(quizQuestions).values([
      { id: "qq-1", contentId: "content-1", question: "Qu'est-ce qu'un trou noir ?", options: ["Une étoile très brillante", "Une région où la gravité est si forte que rien ne peut s'en échapper", "Un trou dans l'espace vide", "Une planète sans lumière"], correctOptionIndex: 1, explanation: "Un trou noir est une région de l'espace-temps où la gravité est si intense que rien, pas même la lumière, ne peut s'en échapper.", order: 0 },
      { id: "qq-2", contentId: "content-1", question: "Comment se forme un trou noir stellaire ?", options: ["Par collision de planètes", "Par l'effondrement d'une étoile massive", "Par explosion du Big Bang", "Par refroidissement d'une nébuleuse"], correctOptionIndex: 1, explanation: "Un trou noir stellaire se forme quand une étoile massive (plus de 20 fois le Soleil) s'effondre sur elle-même en fin de vie.", order: 1 },
      { id: "qq-3", contentId: "content-3", question: "Quelle est la forme générale d'une équation du second degré ?", options: ["ax + b = 0", "ax² + bx + c = 0", "ax³ + bx² + cx + d = 0", "a/x + b = 0"], correctOptionIndex: 1, explanation: "La forme générale est ax² + bx + c = 0 avec a ≠ 0", order: 0 },
      { id: "qq-4", contentId: "content-3", question: "Que représente le discriminant Δ ?", options: ["La somme des racines", "Le produit des racines", "Il détermine le nombre de solutions", "La valeur de x"], correctOptionIndex: 2, explanation: "Δ = b² - 4ac détermine si l'équation a 0, 1 ou 2 solutions réelles", order: 1 },
      { id: "qq-5", contentId: "content-3", question: "Si Δ > 0, combien de solutions réelles ?", options: ["0", "1", "2", "Infini"], correctOptionIndex: 2, explanation: "Quand Δ > 0, il y a deux solutions réelles distinctes", order: 2 },
      { id: "qq-6", contentId: "content-5", question: "Quel langage est utilisé pour programmer Arduino ?", options: ["Python", "C/C++", "Java", "JavaScript"], correctOptionIndex: 1, explanation: "Arduino utilise un langage basé sur C/C++ avec des fonctions spécifiques comme setup() et loop().", order: 0 },
      { id: "qq-7", contentId: "content-5", question: "Que signifie LED ?", options: ["Light Energy Device", "Light Emitting Diode", "Low Energy Display", "Laser Emitting Device"], correctOptionIndex: 1, explanation: "LED signifie Light Emitting Diode (diode électroluminescente).", order: 1 },
      { id: "qq-8", contentId: "content-8", question: "Quelle est la loi d'Ohm ?", options: ["P = UI", "U = R × I", "E = mc²", "F = ma"], correctOptionIndex: 1, explanation: "La loi d'Ohm établit que la tension U est égale au produit de la résistance R par l'intensité I.", order: 0 },
      { id: "qq-9", contentId: "content-8", question: "Quelle unité mesure la résistance électrique ?", options: ["Ampère", "Volt", "Ohm", "Watt"], correctOptionIndex: 2, explanation: "L'ohm (Ω) est l'unité de mesure de la résistance électrique.", order: 1 },
      { id: "qq-10", contentId: "content-9", question: "Quel phénomène permet aux panneaux solaires de produire de l'électricité ?", options: ["L'effet de serre", "L'effet photovoltaïque", "La fusion nucléaire", "L'effet Doppler"], correctOptionIndex: 1, explanation: "L'effet photovoltaïque convertit l'énergie lumineuse en énergie électrique.", order: 0 },
      { id: "qq-11", contentId: "content-9", question: "De quel matériau sont principalement faits les panneaux solaires ?", options: ["Cuivre", "Aluminium", "Silicium", "Fer"], correctOptionIndex: 2, explanation: "Le silicium est le semi-conducteur principal utilisé dans les cellules photovoltaïques.", order: 1 },
      { id: "qq-12", contentId: "content-10", question: "Quel pourcentage de l'univers est composé de matière noire ?", options: ["5%", "15%", "27%", "50%"], correctOptionIndex: 2, explanation: "La matière noire compose environ 27% de l'univers, tandis que la matière ordinaire n'en représente que 5%.", order: 0 },
      { id: "qq-13", contentId: "content-10", question: "Pourquoi la matière noire est-elle appelée 'noire' ?", options: ["Elle est de couleur noire", "Elle n'émet pas de lumière détectable", "Elle absorbe toute la lumière", "Elle se trouve dans les trous noirs"], correctOptionIndex: 1, explanation: "La matière noire est 'noire' car elle n'émet, n'absorbe ni ne réfléchit la lumière.", order: 1 },
      { id: "qq-14", contentId: "content-11", question: "Quels récepteurs détectent la douleur ?", options: ["Photorécepteurs", "Nocicepteurs", "Mécanorécepteurs", "Thermorécepteurs"], correctOptionIndex: 1, explanation: "Les nocicepteurs sont des récepteurs sensoriels spécialisés dans la détection de la douleur.", order: 0 },
      { id: "qq-15", contentId: "content-11", question: "Où le signal de douleur est-il principalement traité ?", options: ["Dans le coeur", "Dans le cerveau", "Dans la moelle épinière", "Dans le foie"], correctOptionIndex: 1, explanation: "Le cerveau interprète et traite les signaux de douleur, notamment dans le cortex somatosensoriel.", order: 1 },
      { id: "qq-16", contentId: "content-14", question: "Qui a dirigé l'équipe de développement du logiciel Apollo ?", options: ["Alan Turing", "Margaret Hamilton", "Grace Hopper", "Ada Lovelace"], correctOptionIndex: 1, explanation: "Margaret Hamilton a dirigé l'équipe du MIT qui a développé le logiciel de navigation d'Apollo.", order: 0 },
      { id: "qq-17", contentId: "content-14", question: "En quelle année le premier alunissage a-t-il eu lieu ?", options: ["1965", "1967", "1969", "1971"], correctOptionIndex: 2, explanation: "Apollo 11 a atterri sur la Lune le 20 juillet 1969.", order: 1 },
      { id: "qq-18", contentId: "content-15", question: "Quel protocole est utilisé pour naviguer sur le web ?", options: ["FTP", "HTTP/HTTPS", "SMTP", "SSH"], correctOptionIndex: 1, explanation: "HTTP (HyperText Transfer Protocol) et sa version sécurisée HTTPS sont les protocoles du web.", order: 0 },
      { id: "qq-19", contentId: "content-15", question: "Comment les données voyagent-elles entre les continents ?", options: ["Par satellite uniquement", "Par ondes radio", "Par câbles sous-marins à fibre optique", "Par Wi-Fi longue portée"], correctOptionIndex: 2, explanation: "Plus de 95% du trafic intercontinental passe par des câbles sous-marins à fibre optique.", order: 1 },
      { id: "qq-20", contentId: "content-16", question: "Qu'est-ce qu'un algorithme ?", options: ["Un type d'ordinateur", "Une suite d'instructions pour résoudre un problème", "Un langage de programmation", "Un logiciel antivirus"], correctOptionIndex: 1, explanation: "Un algorithme est une suite finie d'instructions ordonnées permettant de résoudre un problème.", order: 0 },
      { id: "qq-21", contentId: "content-16", question: "Quel algorithme est utilisé pour trier des éléments ?", options: ["Algorithme de Dijkstra", "Algorithme de tri à bulles", "Algorithme RSA", "Algorithme PageRank"], correctOptionIndex: 1, explanation: "Le tri à bulles est un algorithme simple de tri qui compare les éléments adjacents.", order: 1 },
      { id: "qq-22", contentId: "content-18", question: "Quel est le gratte-ciel le plus haut du monde en 2024 ?", options: ["Empire State Building", "Shanghai Tower", "Burj Khalifa", "One World Trade Center"], correctOptionIndex: 2, explanation: "Le Burj Khalifa à Dubaï culmine à 828 mètres, ce qui en fait le plus haut bâtiment du monde.", order: 0 },
      { id: "qq-23", contentId: "content-18", question: "Pourquoi les gratte-ciel oscillent-ils au vent ?", options: ["Erreur de construction", "Pour absorber l'énergie du vent et éviter de casser", "À cause des tremblements de terre", "Car les matériaux sont défectueux"], correctOptionIndex: 1, explanation: "La flexibilité est voulue : elle permet au bâtiment d'absorber l'énergie du vent sans se briser.", order: 1 },
      { id: "qq-24", contentId: "content-21", question: "Quelle loi de Newton explique la propulsion d'une fusée ?", options: ["Première loi (inertie)", "Deuxième loi (F=ma)", "Troisième loi (action-réaction)", "Loi de la gravitation"], correctOptionIndex: 2, explanation: "La troisième loi de Newton (action-réaction) : les gaz éjectés vers le bas poussent la fusée vers le haut.", order: 0 },
      { id: "qq-25", contentId: "content-21", question: "Quelle vitesse une fusée doit-elle atteindre pour quitter la Terre ?", options: ["1 000 km/h", "11 200 km/h", "28 000 km/h", "100 000 km/h"], correctOptionIndex: 1, explanation: "La vitesse de libération terrestre est d'environ 11 200 km/h (11,2 km/s).", order: 1 },
      { id: "qq-26", contentId: "content-22", question: "Quelle est la valeur approchée de Pi ?", options: ["2,14159", "3,14159", "4,14159", "3,41592"], correctOptionIndex: 1, explanation: "Pi (π) est approximativement égal à 3,14159... C'est un nombre irrationnel avec des décimales infinies.", order: 0 },
      { id: "qq-27", contentId: "content-22", question: "Que mesure Pi ?", options: ["L'aire d'un cercle", "Le rapport entre la circonférence et le diamètre", "Le rayon d'un cercle", "La diagonale d'un carré"], correctOptionIndex: 1, explanation: "Pi est le rapport constant entre la circonférence d'un cercle et son diamètre.", order: 1 },
      { id: "qq-28", contentId: "content-23", question: "Dans l'énigme du pont, combien de personnes doivent traverser ?", options: ["2", "3", "4", "5"], correctOptionIndex: 2, explanation: "Quatre personnes doivent traverser le pont avant l'arrivée des zombies.", order: 0 },
      { id: "qq-29", contentId: "content-23", question: "Quel concept mathématique est au coeur de cette énigme ?", options: ["La trigonométrie", "L'optimisation et la logique", "Les fractions", "Les statistiques"], correctOptionIndex: 1, explanation: "L'énigme demande d'optimiser le temps de traversée en utilisant la logique combinatoire.", order: 1 },
      { id: "qq-30", contentId: "content-24", question: "Que signifie 'surbooking' ?", options: ["Annulation de vol", "Vente de plus de billets que de places", "Retard de vol", "Vol avec escale"], correctOptionIndex: 1, explanation: "Le surbooking consiste à vendre plus de billets que de sièges disponibles, en anticipant les annulations.", order: 0 },
      { id: "qq-31", contentId: "content-24", question: "Quel outil mathématique permet de calculer le risque de surbooking ?", options: ["La géométrie", "Les probabilités et statistiques", "L'algèbre linéaire", "Le calcul différentiel"], correctOptionIndex: 1, explanation: "Les compagnies utilisent les probabilités pour estimer le taux de no-show et décider du niveau de surbooking.", order: 1 },
      { id: "qq-32", contentId: "content-6", question: "Combien de planètes composent notre système solaire ?", options: ["7", "8", "9", "10"], correctOptionIndex: 1, explanation: "Notre système solaire compte 8 planètes depuis que Pluton a été reclassée en planète naine en 2006.", order: 0 },
      { id: "qq-33", contentId: "content-6", question: "Quelle est la plus grande planète du système solaire ?", options: ["Saturne", "Neptune", "Jupiter", "Uranus"], correctOptionIndex: 2, explanation: "Jupiter est la plus grande planète avec un diamètre de 139 820 km, soit 11 fois celui de la Terre.", order: 1 },
      { id: "qq-34", contentId: "content-12", question: "Quelle hormone est appelée 'l'hormone de l'amour' ?", options: ["Adrénaline", "Cortisol", "Ocytocine", "Insuline"], correctOptionIndex: 2, explanation: "L'ocytocine est souvent appelée l'hormone de l'amour car elle est libérée lors de câlins et de liens sociaux.", order: 0 },
      { id: "qq-35", contentId: "content-13", question: "Quelle force maintient les planètes en orbite autour du Soleil ?", options: ["La force électromagnétique", "La force gravitationnelle", "La force nucléaire", "La force centrifuge"], correctOptionIndex: 1, explanation: "La force gravitationnelle, décrite par Newton puis Einstein, maintient les planètes en orbite autour du Soleil.", order: 0 },
      { id: "qq-36", contentId: "content-13", question: "Qui a formulé la loi de la gravitation universelle ?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Johannes Kepler"], correctOptionIndex: 1, explanation: "Isaac Newton a formulé la loi de la gravitation universelle en 1687 dans ses Principia Mathematica.", order: 1 },
      { id: "qq-37", contentId: "content-17", question: "Qu'est-ce qu'une variable en programmation ?", options: ["Une erreur dans le code", "Un espace mémoire qui stocke une valeur", "Un type de processeur", "Un langage de programmation"], correctOptionIndex: 1, explanation: "Une variable est un espace mémoire nommé qui permet de stocker et manipuler des données dans un programme.", order: 0 },
      { id: "qq-38", contentId: "content-17", question: "Qu'est-ce qu'une boucle en programmation ?", options: ["Un bug informatique", "Une instruction qui se répète", "Un type de variable", "Un commentaire dans le code"], correctOptionIndex: 1, explanation: "Une boucle est une structure qui permet de répéter un bloc d'instructions un certain nombre de fois.", order: 1 },
      { id: "qq-39", contentId: "content-19", question: "Dans quels produits du quotidien trouve-t-on de la chimie ?", options: ["Uniquement les médicaments", "Les cosmétiques, aliments et vêtements", "Seulement les produits industriels", "Aucun produit naturel"], correctOptionIndex: 1, explanation: "La chimie est présente partout : cosmétiques, aliments, textiles, plastiques, produits d'entretien et bien plus.", order: 0 },
      { id: "qq-40", contentId: "content-20", question: "Quelle planète est la plus proche du Soleil ?", options: ["Vénus", "Terre", "Mercure", "Mars"], correctOptionIndex: 2, explanation: "Mercure est la planète la plus proche du Soleil, à une distance moyenne de 58 millions de km.", order: 0 },
      { id: "qq-41", contentId: "content-20", question: "Pourquoi un modèle réduit du système solaire est-il utile ?", options: ["Pour décorer", "Pour comprendre les échelles et distances entre planètes", "Pour remplacer un télescope", "Pour calculer la gravité"], correctOptionIndex: 1, explanation: "Un modèle réduit aide à visualiser les immenses distances et les tailles relatives des planètes.", order: 1 },
    ]);

    await db.insert(badges).values([
      { id: "badge-1", name: "Premier Pas", description: "Complète ton premier contenu", icon: "footprints", category: "contribution", requirement: "Complete 1 content", xpRequired: 0 },
      { id: "badge-2", name: "Explorateur", description: "Explore 10 contenus différents", icon: "compass", category: "contribution", requirement: "View 10 contents", xpRequired: 100 },
      { id: "badge-3", name: "Expert Quiz", description: "Obtiens 100% à un quiz", icon: "trophy", category: "performance", requirement: "Perfect quiz score", xpRequired: 200 },
      { id: "badge-4", name: "Commentateur", description: "Écris 5 commentaires", icon: "message-circle", category: "social", requirement: "Write 5 comments", xpRequired: 50 },
      { id: "badge-5", name: "Partageur", description: "Partage 3 contenus", icon: "share-2", category: "social", requirement: "Share 3 contents", xpRequired: 75 },
      { id: "badge-6", name: "Série de 7", description: "7 jours de streak", icon: "flame", category: "performance", requirement: "7 day streak", xpRequired: 300 },
      { id: "badge-7", name: "Scientifique", description: "Complète 5 contenus de Science", icon: "flask-conical", category: "contribution", requirement: "Complete 5 science contents", xpRequired: 150 },
      { id: "badge-8", name: "Technologue", description: "Complète 5 contenus de Technologie", icon: "cpu", category: "contribution", requirement: "Complete 5 technology contents", xpRequired: 150 },
      { id: "badge-9", name: "Ingénieur", description: "Complète 5 contenus d'Ingénierie", icon: "wrench", category: "contribution", requirement: "Complete 5 engineering contents", xpRequired: 150 },
      { id: "badge-10", name: "Mathématicien", description: "Complète 5 contenus de Mathématiques", icon: "calculator", category: "contribution", requirement: "Complete 5 math contents", xpRequired: 150 },
      { id: "badge-11", name: "Mentor", description: "Atteins le niveau Mentor", icon: "graduation-cap", category: "special", requirement: "Reach Mentor level", xpRequired: 5000 },
      { id: "badge-12", name: "Social Star", description: "Obtiens 10 followers", icon: "star", category: "social", requirement: "Get 10 followers", xpRequired: 200 },
    ]);

    await db.insert(missions).values([
      { id: "mission-1", missionType: "watch_videos", title: "Explorateur du jour", description: "Regarde 3 vidéos de science", targetValue: 3, currentProgress: 1, xpReward: 100, frequency: "daily", category: "science", completed: false, expiresAt: null },
      { id: "mission-2", missionType: "complete_quiz", title: "Maître des quiz", description: "Complète 2 quiz cette semaine", targetValue: 2, currentProgress: 0, xpReward: 150, frequency: "weekly", category: null, completed: false, expiresAt: null },
      { id: "mission-3", missionType: "join_salon", title: "Socialise !", description: "Rejoins un nouveau salon", targetValue: 1, currentProgress: 0, xpReward: 75, frequency: "one_time", category: null, completed: false, expiresAt: null },
      { id: "mission-4", missionType: "comment", title: "Participe à la discussion", description: "Commente 2 publications", targetValue: 2, currentProgress: 1, xpReward: 50, frequency: "daily", category: null, completed: false, expiresAt: null },
      { id: "mission-5", missionType: "streak", title: "Série de 7 jours", description: "Connecte-toi 7 jours de suite", targetValue: 7, currentProgress: 3, xpReward: 300, frequency: "one_time", category: null, completed: false, expiresAt: null },
      { id: "mission-6", missionType: "share_content", title: "Ambassadeur STEM", description: "Partage 1 contenu avec un ami", targetValue: 1, currentProgress: 1, xpReward: 50, frequency: "daily", category: null, completed: true, expiresAt: null },
      { id: "mission-7", missionType: "create_content", title: "Créateur de contenu", description: "Publie un nouveau contenu", targetValue: 1, currentProgress: 0, xpReward: 200, frequency: "weekly", category: null, completed: false, expiresAt: null },
    ]);

    await db.insert(commentsTable).values([
      { id: "comment-1", contentId: "content-1", userId: "lb-user-1", authorName: "Dr. Marie Curie", text: "Excellent contenu ! Les trous noirs sont fascinants.", parentId: null, likes: 5, createdAt: new Date(Date.now() - 3600000).toISOString() },
      { id: "comment-2", contentId: "content-2", userId: "lb-user-2", authorName: "Alan Turing", text: "Bonne introduction à l'IA. J'aurais ajouté un mot sur le deep learning.", parentId: null, likes: 3, createdAt: new Date(Date.now() - 7200000).toISOString() },
      { id: "comment-3", contentId: "content-1", userId: "lb-user-3", authorName: "Ada Lovelace", text: "Très bien expliqué, merci pour ce partage !", parentId: null, likes: 2, createdAt: new Date(Date.now() - 1800000).toISOString() },
      { id: "comment-4", contentId: "content-1", userId: "lb-user-2", authorName: "Alan Turing", text: "Tout à fait d'accord ! La singularité est le concept le plus intrigant.", parentId: "comment-1", likes: 1, createdAt: new Date(Date.now() - 3000000).toISOString() },
      { id: "comment-5", contentId: "content-1", userId: "lb-user-4", authorName: "Pierre Fermat", text: "Les maths derrière la relativité générale sont magnifiques.", parentId: "comment-1", likes: 3, createdAt: new Date(Date.now() - 2400000).toISOString() },
      { id: "comment-6", contentId: "content-2", userId: "lb-user-5", authorName: "Nikola Tesla", text: "Le deep learning est effectivement crucial pour comprendre l'IA moderne.", parentId: "comment-2", likes: 2, createdAt: new Date(Date.now() - 6000000).toISOString() },
    ]);

    await db.insert(activities).values([
      { id: "act-1", userId: "lb-user-1", username: "Dr. Marie Curie", activityType: "content_created", description: "a publie un nouveau contenu : Comment fonctionne un trou noir ?", metadata: null, createdAt: new Date(Date.now() - 1800000).toISOString() },
      { id: "act-2", userId: "lb-user-2", username: "Alan Turing", activityType: "quiz_completed", description: "a complete un quiz en Technologie avec 95%", metadata: null, createdAt: new Date(Date.now() - 3600000).toISOString() },
      { id: "act-3", userId: "lb-user-3", username: "Ada Lovelace", activityType: "room_joined", description: "a rejoint le salon Robotique Club", metadata: null, createdAt: new Date(Date.now() - 7200000).toISOString() },
      { id: "act-4", userId: "lb-user-4", username: "Pierre Fermat", activityType: "badge_earned", description: "a obtenu le badge Expert Quiz", metadata: null, createdAt: new Date(Date.now() - 10800000).toISOString() },
      { id: "act-5", userId: "lb-user-5", username: "Nikola Tesla", activityType: "level_up", description: "est passe au niveau Explorateur", metadata: null, createdAt: new Date(Date.now() - 14400000).toISOString() },
      { id: "act-6", userId: "lb-user-1", username: "Dr. Marie Curie", activityType: "mission_completed", description: "a complete la mission Explorateur du jour", metadata: null, createdAt: new Date(Date.now() - 18000000).toISOString() },
      { id: "act-7", userId: "lb-user-2", username: "Alan Turing", activityType: "content_created", description: "a publie un nouveau contenu : L'intelligence artificielle expliquee simplement", metadata: null, createdAt: new Date(Date.now() - 21600000).toISOString() },
      { id: "act-8", userId: "lb-user-3", username: "Ada Lovelace", activityType: "quiz_completed", description: "a complete un quiz en Mathematiques avec 100%", metadata: null, createdAt: new Date(Date.now() - 25200000).toISOString() },
      { id: "act-9", userId: "lb-user-4", username: "Pierre Fermat", activityType: "content_created", description: "a publie un nouveau contenu : Le theoreme de Pythagore dans la vraie vie", metadata: null, createdAt: new Date(Date.now() - 28800000).toISOString() },
      { id: "act-10", userId: "lb-user-5", username: "Nikola Tesla", activityType: "room_joined", description: "a rejoint le salon Ingenieurs en herbe", metadata: null, createdAt: new Date(Date.now() - 32400000).toISOString() },
    ]);

    await db.insert(roomPosts).values([
      { id: "rp-1", roomId: "room-1", userId: "lb-user-1", username: "Dr. Marie Curie", text: "Qui a vu le dernier documentaire sur les trous noirs ? Les images du James Webb sont incroyables !", likes: 12, createdAt: new Date(Date.now() - 1800000).toISOString() },
      { id: "rp-2", roomId: "room-1", userId: "lb-user-4", username: "Pierre Fermat", text: "Je recommande le livre 'Cosmos' de Carl Sagan pour comprendre les bases de l'astrophysique.", likes: 8, createdAt: new Date(Date.now() - 5400000).toISOString() },
      { id: "rp-3", roomId: "room-1", userId: "lb-user-3", username: "Ada Lovelace", text: "Est-ce que quelqu'un peut m'expliquer la difference entre fusion et fission nucleaire ?", likes: 5, createdAt: new Date(Date.now() - 10800000).toISOString() },
      { id: "rp-4", roomId: "room-2", userId: "lb-user-2", username: "Alan Turing", text: "Je viens de terminer mon premier projet avec React et Node.js. Le full-stack, c'est passionnant !", likes: 15, createdAt: new Date(Date.now() - 3600000).toISOString() },
      { id: "rp-5", roomId: "room-2", userId: "lb-user-5", username: "Nikola Tesla", text: "Quelqu'un a deja utilise un Raspberry Pi pour un projet IoT ?", likes: 9, createdAt: new Date(Date.now() - 7200000).toISOString() },
      { id: "rp-6", roomId: "room-2", userId: "lb-user-3", username: "Ada Lovelace", text: "L'IA generative va revolutionner la facon dont on apprend.", likes: 11, createdAt: new Date(Date.now() - 14400000).toISOString() },
      { id: "rp-7", roomId: "room-1", userId: "lb-user-5", username: "Nikola Tesla", text: "La physique quantique me fascine. Avez-vous des ressources pour les debutants ?", likes: 7, createdAt: new Date(Date.now() - 21600000).toISOString() },
    ]);

    console.log("Database seeded successfully");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}
